#!/bin/bash

for start in {2..4..2}; do
	for ((i=$start; i<=500; i++)); do
		mkdir SP$start
		mkdir /mnt/data/SP_data/SP$start
		cp SP_Template SP$start/SP$start\_$i.foma
		sed -i "s/<LEN>/$i/g" SP$start/SP$start\_$i.foma
		if [ $start = 2 ]
		then
			sed -i "s/<FORBIDDEN>/a b | b c/g" SP$start/SP$start\_$i.foma
		elif [ $start = 4 ]
		then
			sed -i "s/<FORBIDDEN>/a b b a | b c c b/g" SP$start/SP$start\_$i.foma
		fi

		echo "Processing file: "SP$start/SP$start\_$i.foma
		touch /mnt/data/SP_data/SP$start/SP$start\_$i.dat
		foma -f SP$start/SP$start\_$i.foma > /mnt/data/SP_data/SP$start/SP$start\_$i.dat
	done
done